/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemovalistsIndexRouteImport } from './routes/removalists/index'
import { Route as ServicesServiceRouteImport } from './routes/services/$service'
import { Route as RemovalistsAreaRouteImport } from './routes/removalists/$area'
import { Route as Guides7MovingMistakesRouteImport } from './routes/guides/7-moving-mistakes'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalistsIndexRoute = RemovalistsIndexRouteImport.update({
  id: '/removalists/',
  path: '/removalists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovalistsAreaRoute = RemovalistsAreaRouteImport.update({
  id: '/removalists/$area',
  path: '/removalists/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const Guides7MovingMistakesRoute = Guides7MovingMistakesRouteImport.update({
  id: '/guides/7-moving-mistakes',
  path: '/guides/7-moving-mistakes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/guides/7-moving-mistakes': typeof Guides7MovingMistakesRoute
  '/removalists/$area': typeof RemovalistsAreaRoute
  '/services/$service': typeof ServicesServiceRoute
  '/removalists/': typeof RemovalistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/guides/7-moving-mistakes': typeof Guides7MovingMistakesRoute
  '/removalists/$area': typeof RemovalistsAreaRoute
  '/services/$service': typeof ServicesServiceRoute
  '/removalists': typeof RemovalistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/guides/7-moving-mistakes': typeof Guides7MovingMistakesRoute
  '/removalists/$area': typeof RemovalistsAreaRoute
  '/services/$service': typeof ServicesServiceRoute
  '/removalists/': typeof RemovalistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/guides/7-moving-mistakes'
    | '/removalists/$area'
    | '/services/$service'
    | '/removalists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/guides/7-moving-mistakes'
    | '/removalists/$area'
    | '/services/$service'
    | '/removalists'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/guides/7-moving-mistakes'
    | '/removalists/$area'
    | '/services/$service'
    | '/removalists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  Guides7MovingMistakesRoute: typeof Guides7MovingMistakesRoute
  RemovalistsAreaRoute: typeof RemovalistsAreaRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
  RemovalistsIndexRoute: typeof RemovalistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removalists/': {
      id: '/removalists/'
      path: '/removalists'
      fullPath: '/removalists/'
      preLoaderRoute: typeof RemovalistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removalists/$area': {
      id: '/removalists/$area'
      path: '/removalists/$area'
      fullPath: '/removalists/$area'
      preLoaderRoute: typeof RemovalistsAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/7-moving-mistakes': {
      id: '/guides/7-moving-mistakes'
      path: '/guides/7-moving-mistakes'
      fullPath: '/guides/7-moving-mistakes'
      preLoaderRoute: typeof Guides7MovingMistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  Guides7MovingMistakesRoute: Guides7MovingMistakesRoute,
  RemovalistsAreaRoute: RemovalistsAreaRoute,
  ServicesServiceRoute: ServicesServiceRoute,
  RemovalistsIndexRoute: RemovalistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
